version: 2

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    cooldown:
      default-days: 15
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    cooldown:
      default-days: 15
