name: NR1 Library Deprecation Checks

on: [push, workflow_dispatch]

jobs:
  nr1_lib_deprecations:
    name: Run NR1 Library Deprecation Checks
    runs-on: ubuntu-latest
    steps:
      - name: Test Default Branch
        id: default-branch
        uses: actions/github-script@4aed96e0ba636e3df2423e6887c9a83ef8522d6d # v2
        with:
          script: |
            const data = await github.repos.get(context.repo)
            return data.data && data.data.default_branch === context.ref.split('/').slice(-1)[0]
      - name: Checkout Self
        if: ${{ steps.default-branch.outputs.result == 'true' }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run Repolinter
        if: ${{ steps.default-branch.outputs.result == 'true' }}
        uses: newrelic/repolinter-action@3f4448f855c351e9695b24524a4111c7847b84cb # v1
        with:
          output_name: 'NR1 library deprecation issues'
          label_name: 'nr1-deprecations'
          label_color: '800000'
          # FIXME: Replace with the appropriate ruleset URL
          config_url: https://raw.githubusercontent.com/newrelic/.github/main/repolinter-rulesets/nr1-lib-deprecations.yml
          output_type: issue
